runtime: nodejs20

env_variables:
  REACT_APP_CLIENT_ID: 138466072982-adt7rp94n1i0vam4k89dniaa4pk0s3d2.apps.googleusercontent.com

handlers:
  # Serve static assets (JS, CSS, images, etc.)
  - url: /(.*\.(js|css|png|jpg|jpeg|gif|svg|ico|json|map))
    static_files: build/\1
    upload: build/(.*\.(js|css|png|jpg|jpeg|gif|svg|ico|json|map))

  # React Router fallback
  - url: /.*
    static_files: build/index.html
    upload: build/index.html
